name: netreg
channels:
  - r
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - bioconductor-qvalue=2.2.2
  - dask=2.9.1
  - dask-ml=1.0.0
  - matplotlib=3.1.0
  - networkx=2.4
  - numpy=1.16.5
  - pandas=0.24.2
  - python=3.6.9
  - pytest=5.0.0
  - pytorch=1.2.0
  - r=3.6.0
  - r-argparse=2.0.1
  - r-base=3.6.0
  - r-devtools=2.0.2
  - r-ggplot2=3.1.1
  - r-rcolorbrewer=1.1_2
  - scikit-learn=0.21.2
  - scipy=1.3.2
  - seaborn=0.9.0
  - torchvision=0.4.0

